import platform
import shlex
from glob import glob
from os import environ, pathsep
from os.path import basename, dirname, join

from setuptools import Extension, setup
from setuptools_scm import get_version

dconv_includes = [
    dir
    for dir in environ.get(
        "UJSON_BUILD_DC_INCLUDES",
        "./src/ujson/deps/double-conversion/double-conversion",
    ).split(pathsep)
    if dir
]
dconv_libs = shlex.split(environ.get("UJSON_BUILD_DC_LIBS", ""))
dconv_source_files = []
if not dconv_libs:
    dconv_source_files.extend(
        glob("./src/ujson/deps/double-conversion/double-conversion/*.cc")
    )
dconv_source_files.append("./src/ujson/lib/dconv_wrapper.cc")

if platform.system() == "Linux" and environ.get("UJSON_BUILD_NO_STRIP", "0") not in (
    "1",
    "True",
):
    strip_flags = ["-Wl,--strip-all"]
else:
    strip_flags = []


def local_scheme(version):
    """Skip the local version (eg. +xyz of 0.6.1.dev4+gdf99fe2)
    to be able to upload to Test PyPI"""
    return ""


def env_flag(name, default="0"):
    return environ.get(name, default) in ("1", "True", "true")


version = get_version(local_scheme=local_scheme)
build_hpy = env_flag("UJSON_BUILD_HPY")
build_cpython_ext = env_flag("UJSON_BUILD_CPYTHON_EXT", "0" if build_hpy else "1")

if build_hpy:
    from hpy import devel as hpy_devel
    from distutils import log

    def _write_stub_without_pkg_resources(self, output_dir, ext, compile=False):
        if (
            not hasattr(ext, "hpy_abi")
            or self.distribution.hpy_abi not in ("universal", "hybrid")
        ):
            return self._mixin_super.write_stub(self, output_dir, ext, compile=compile)

        pkgs = ext._full_name.split(".")
        if compile:
            pkgs = [pkgs[-1]]
        stub_file = join(output_dir, *pkgs) + ".py"
        log.info(
            "writing hpy universal stub loader for %s to %s",
            ext._full_name,
            stub_file,
        )

        ext_file = basename(ext._file_name)
        module_name = ext_file.split(".")[0]
        stub_source = f"""
# DO NOT EDIT THIS FILE!
# This file is automatically generated by hpy

def __bootstrap__():

    from os import environ
    from os.path import dirname, join
    from sys import modules
    from hpy.universal import _load_bootstrap
    ext_filepath = join(dirname(__file__), {ext_file!r})
    m = _load_bootstrap({module_name!r}, __name__, __package__, ext_filepath,
                        __loader__, __spec__, environ)
    modules[__name__] = m

__bootstrap__()
"""
        if not self.dry_run:
            with open(stub_file, "w") as f:
                f.write(stub_source)

            ext_stub_file = join(
                dirname(self.get_ext_fullpath(ext.name)), module_name + ".py"
            )
            if ext_stub_file != stub_file:
                log.info(
                    "writing hpy universal sibling stub loader for %s to %s",
                    ext._full_name,
                    ext_stub_file,
                )
                with open(ext_stub_file, "w") as f:
                    f.write(stub_source)

    hpy_devel.build_ext_hpy_mixin.write_stub = _write_stub_without_pkg_resources

cpython_ext_modules = []
if build_cpython_ext:
    cpython_ext_modules.append(
        Extension(
            "ujson",
            sources=dconv_source_files
            + [
                "./src/ujson/python/ujson.c",
                "./src/ujson/python/objToJSON.c",
                "./src/ujson/python/JSONtoObj.c",
                "./src/ujson/lib/ultrajsonenc.c",
                "./src/ujson/lib/ultrajsondec.c",
            ],
            include_dirs=["./src/ujson/python", "./src/ujson/lib"] + dconv_includes,
            define_macros=[("UJSON_VERSION", f'"{version}"')],
            extra_compile_args=["-D_GNU_SOURCE"],
            extra_link_args=["-lstdc++", "-lm"] + dconv_libs + strip_flags,
        )
    )

hpy_ext_modules = []
if build_hpy:
    hpy_ext_modules.append(
        Extension(
            "ujson_hpy",
            sources=dconv_source_files
            + [
                "./src/ujson/python/ujson_hpy.c",
                "./src/ujson/lib/ultrajsonenc.c",
                "./src/ujson/lib/ultrajsondec.c",
            ],
            include_dirs=["./src/ujson/lib"] + dconv_includes,
            define_macros=[("UJSON_VERSION", f'"{version}"')],
            extra_compile_args=["-D_GNU_SOURCE"],
            extra_link_args=["-lstdc++", "-lm"] + dconv_libs + strip_flags,
        )
    )

setup(
    hpy_ext_modules=hpy_ext_modules,
    ext_modules=cpython_ext_modules,
    setup_requires=["hpy"] if build_hpy else [],
    use_scm_version={"local_scheme": local_scheme},
)
