[tox]
requires =
    tox>=4.2
env_list =
    lint
    hpy-cpython
    hpy-universal
    py{py3, 314, 313, 312, 311, 310}

[testenv]
deps =
    pytest
pass_env =
    FORCE_COLOR
set_env =
    UJSON_BUILD_CPYTHON_EXT = 1
    UJSON_BUILD_HPY = 0
commands =
    {envpython} -m pytest {posargs}

[testenv:lint]
skip_install = true
deps =
    prek
pass_env =
    PREK_COLOR
commands =
    prek run --all-files --show-diff-on-failure

[testenv:hpy-cpython]
skip_install = true
deps =
    hpy<0.10,>=0.9
    pytest
    setuptools
    setuptools-scm
set_env =
    UJSON_BUILD_CPYTHON_EXT = 0
    UJSON_BUILD_HPY = 1
commands =
    bash scripts/hpy-test.sh cpython {posargs}

[testenv:hpy-universal]
skip_install = true
deps =
    hpy<0.10,>=0.9
    pytest
    setuptools
    setuptools-scm
set_env =
    UJSON_BUILD_CPYTHON_EXT = 0
    UJSON_BUILD_HPY = 1
commands =
    bash scripts/hpy-test.sh universal {posargs}
